excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://rubicundheart.github.io
title: Nuance Interactive
email: amber@nuance-interactive.com
author: Amber
description: Northern Colorado freelance designer and front-end developer
paginate: 6
google_analytics: 